export const treeData = [
  { day: 24, ornament: '*', ornamentLit: '--*--' },
  { day: 23, ornament: '>o<' },
  { day: 22, ornament: '>>o<<' },
  { day: 21, ornament: '>>@>@<<' },
  { day: 20, ornament: '>O<<o>>O<' },
  { day: 19, ornament: '>>O>>O<O<<<' },
  { day: 18, ornament: '>>O>>O<<o>@<<' },
  { day: 17, ornament: '>>O>*<o>>>*>@<<' },
  { day: 16, ornament: '>>@>o<<*<<*<<*<<<' },
  { day: 15, ornament: '>>o<<o<o<<@<<O>O<<<' },
  { day: 14, ornament: '>>*>>o>>o>o>>*>>@<<<<' },
  { day: 13, ornament: '>*<<<*>>o>@>>>*>@<<<o<<' },
  { day: 12, ornament: '>>*<<*>>*>>>*<<@>>@>@>>o<' },
  { day: 11, ornament: '>*>>>*<<<*<<*<@>>@<<<O<<<*<' },
  { day: 10, ornament: '>>@<@<<<O<<o>>>@<o>>@<<<@>o<<' },
  { day: 9, ornament: '>o<@<O<<o>*>>O<o<<o>>>O>*>o<<<<' },
  { day: 8, ornament: '>*<<*>>>o>>>*>>>*>@>>*<<*<<<*>>o<' },
  { day: 7, ornament: '>o>>O>>O>>*>@<o>>@>O<*<<*>>O>>o>O<<' },
  { day: 6, ornament: '>*<o>O<<O<<o<<*<@>@<<*<<*>>@>>>O<<<*<' },
  { day: 5, ornament: '>>*<<<*<<O<<<@>>>O<<<O<<o>>O>>O<<o>>o<<' },
  { day: 4, ornament: '>>@>>>o>@<*>>>*>>@<<<*<<@>>O<O>>*<@<<O<<<' },
  { day: 3, ornament: '>>*>o<<*<<*<<o>*>O<<@>>o>>>*<<<*>>@>>>*<<<<' },
  { day: 2, ornament: '>>*>>>*<<<@>>>o<<*>>>@>>o>>o>>O<<<o>@>>>*<<o<' },
  { day: 1, ornament: '>@<*<<@>>*<o<<O>>>@>O<<@>*>>*>>>o<<@<@<<<o<*>@<' },
  { day: 0, ornament: '||', active: true },
  { day: -1, ornament: '||', active: true },
  { day: -2, ornament: '_  _ __ ___||___ __ _  _', active: true },
];
